version: "3.3"
services:
  database:
    image: "mysql:latest"
    container_name: "database"
    environment:
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - "./docker/dbInit:/docker-entrypoint-initdb.d"
