version: "3.8"

services:
  database:
    image: "mysql:latest"
    container_name: "database"
    environment:
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - "./internal/db:/docker-entrypoint-initdb.d"
